export const cartName = 'cartItems'
export const groupOrder = 'isGroupOrder'
export const groupOrderCustomerId = 'groupOrderCustomerId'
export const isJoinedGroupOrderByLink = 'isJoinedGroupOrderByLink'
export const groupOrderId = 'groupOrderId'