export const cartName = 'cartItems'
export const groupOrder = 'isGroupOrder'
export const groupOrderCustomerId = 'groupOrderCustomerId'
export const isJoinedGroupOrderByLink = 'isJoinedGroupOrderByLink'
export const groupOrderId = 'groupOrderId'
export const groupOrderCode = 'groupOrderCode'
export const groupOrderMemberName = 'groupOrderMemberName'